apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: hw2
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - image: daslapovsky/otus:0.1.3
          name: supercontainer
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configs
                  key: "env"
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configs
                  key: "database.properties.host"
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-configs
                  key: "database.properties.port"
            - name: OTUSAPP2_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secrets
                  key: password
