apiVersion: v1
kind: Secret
metadata:
  name: pg-secrets
  namespace: hw2
type: Opaque
data:
  postgrespassword: {{ .Values.postgres.postgrespassword }}
  password: {{ .Values.postgres.otususerpassword }}
